import {
  Roma,
  Romasingle,
  Venezia,
  Veneziasingle,
  Torino,
  Torinosingle,
  Firenze,
  Firenzesingle,
  Napoli,
  Napolisingle,
  Mocachino,
  Mocachinosingle,
  Capuchino,
  Capuchinosingle,
  Bayleys,
  Bayleyssingle,
  Caramel,
  Caramelsingle,
  blanco,
  blancosingle,
  Cremebrule,
  Cremebrulesingle,
  Cortado,
  Cortadosingle,
  Chocolate,
  Chocolatesingle,
  Avellana,
  Avellanasingle,
  Tradicional,
  Tradicionalsingle,
} from "../../assets/images/index";
const CapsulesData = [
  {
    listImg: Roma,
    singleImg: Romasingle,
    blendName: "Roma",
    to: "Roma",
    description: `Disaster Relief Australia provides disaster response to those affected by natural disasters, be they domestic or international.

By pairing the skills and experiences of military veterans with emergency responders, medical professionals, and technology solutions, Disaster Relief Australia aims to provide the greatest service and impact possible.

The Disaster Relief Blend by Two 14 Coffee Co. is a dark, heavy roast with chocolate notes - the perfect pick-me-up for exhausted emergency responders. A portion of profits will go towards the volunteer efforts of Disaster Relief Australia.`,
    roast: "Dark",
    origin: "Central America, South America, Africa",
    taste: "Rich, Heavy, Chocolate",
    price: 39.0,
    linkTitle: "Disaster relief australia",
    link: "https://disasterreliefaus.org/",
    category: "capsules",
  },
  {
    listImg: Venezia,
    singleImg: Veneziasingle,
    blendName: "Venezia",
    to: "Venezia",
    description:
      "Enjoy a full-flavoured coffee without the caffeine hit, with our medium-roast single-origin decaf coffee. Sourced from Columbia, our water-processed decaf packs in loads of flavour with juicy, sweet acidity and toasted cocoa notes.",
    roast: "Medium",
    origin: "Columbia (water processed)",
    taste: "Juicy sweet acidity, toasted cocoa",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Torino,
    singleImg: Torinosingle,
    blendName: "Torino",
    to: "Torino",
    description: `Our High-Energy Anti-Tiredness (H.E.A.T) Coffee Capsules are the perfect ammunition for those in need of a quick energy infusion! Plant-based and 100% biodegradable and compostable. 
    Nespresso® Compatible Pods.`,
    roast: "",
    origin: "",
    taste: "Strong & Smooth",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Firenze,
    singleImg: Firenzesingle,
    blendName: "Firenze",
    to: "Firenze",
    description: `The Pine
    `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Napoli,
    singleImg: Napolisingle,
    blendName: "Napoli",
    to: "Napoli",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Mocachino,
    singleImg: Mocachinosingle,
    blendName: "Mocachino",
    to: "Mocachino",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Capuchino,
    singleImg: Capuchinosingle,
    blendName: "Capuchino",
    to: "Capuchino",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Bayleys,
    singleImg: Bayleyssingle,
    blendName: "Bayleys",
    to: "Bayleys",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Caramel,
    singleImg: Caramelsingle,
    blendName: "Caramel",
    to: "Caramel",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: blanco,
    singleImg: blancosingle,
    blendName: "Blanco",
    to: "Blanco",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Cremebrule,
    singleImg: Cremebrulesingle,
    blendName: "Cremebrule",
    to: "Cremebrule",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Cortado,
    singleImg: Cortadosingle,
    blendName: "Cortado",
    to: "Cortado",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Chocolate,
    singleImg: Chocolatesingle,
    blendName: "Chocolate",
    to: "Chocolate",
    description: `The Pineapple Express is a veteran-owned and operated coffee company that is dedicated to supporting veterans and their families. They have a range of delicious coffee blends that are perfect for any coffee lover. `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
  {
    listImg: Avellana,
    singleImg: Avellanasingle,
    blendName: "Avellana",
    to: "Avellana",
    description: `
    `,
    roast: "",
    origin: "",
    taste: "",
    price: 39.0,
    linkTitle: "",
    link: "",
    category: "capsules",
  },
 

];

export default CapsulesData;
