name: Deploy to S3

on:
  push:
    branches:
      - main  # Cambia a la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # O la versión que estés utilizando

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run predeploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Cambia a tu región

      - name: Deploy to S3
        run: npm run deploy
